HP meter in card
WildCodeSchool/reims-js-2103-project2-insomniac-battle-of-heroes pull request #30
Opened 2021-05-05 11:51 UTC by tomriiich

2021-05-05 14:52 UTC, rocambille requested changes

2021-05-05 14:52 UTC, rocambille commented on src/components/Game.jsx
> +>>>>>>> Stashed changes
unresolved conflict

2021-05-05 14:52 UTC, rocambille commented
conflicts to resolve

2021-05-06 07:23 UTC, merged

2021-05-06 07:23 UTC, tomriiich commented
I resolved everything I have access to